language: ruby
services:
  - postgresql
rvm:
  - 2.5.1
sudo: required
addons:
  chrome: stable
cache:
  directories:
  - /home/travis/.rvm/
  bundler: true
  yarn: true
before_install:
  - sudo apt-get update && sudo apt-get -y install google-chrome-stable
  - gem install bundler -v 1.16.3
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
  - bundle install
  # - bundle exec rake db:create
  - psql -c 'create database dasha_taxpayer_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
script:
  - "bundle exec rspec"
  - "CHECK_COVERAGE=true bundle exec cucumber"
  - "bundle exec rubocop"
  - "bundle exec reek"
